INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (4970, 'Cassiano', 'Aeroporto de Guerra, Acaiaca, 60150472 Silva / PI', 'rochaapollo@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (0161, 'Silva', 'Praça Camargo, 43, Conjunto Bonsucesso, 56312871 da Rosa / SP', 'heitorcasa-grande@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (4522, 'Vargas e Filhos', 'Alameda Murilo Viana, 5, Alípio De Melo, 54067-969 Câmara da Prata / RR', 'casa-grandearthur-miguel@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (5483, 'Lima', 'Viela de Araújo, 90, Tupi A, 10789658 Pinto Alegre / TO', 'efreitas@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (9814, 'Correia Albuquerque S.A.', 'Conjunto Aurora Freitas, 6, Olhos D''água, 71554308 Lima / BA', 'lucca82@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (3595, 'das Neves', 'Largo Heloísa Novais, 44, Providencia, 58623-780 Moura das Flores / DF', 'qsouza@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (4536, 'Fogaça', 'Setor Cirino, 677, Nova Suíça, 76397-889 Castro Paulista / SP', 'ramoshenry-gabriel@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (4287, 'Oliveira', 'Trecho Julia Costa, 12, Vila Nova Gameleira 2ª Seção, 84699679 Almeida / PE', 'luiz-otavio45@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (5298, 'Santos', 'Quadra de Sales, 48, Ápia, 51958-923 Brito / DF', 'nathanda-conceicao@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (9179, 'Sá', 'Pátio Pinto, 48, Vila Paraíso, 21824956 Porto / DF', 'cassianoana-vitoria@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (72510, 'Pinto S.A.', 'Travessa Moraes, 57, Vila Inestan, 57238206 Vasconcelos das Flores / PB', 'laura70@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (06511, 'das Neves', 'Lago de Moraes, 2, Bairro Das Indústrias Ii, 66204-806 da Mota / DF', 'unascimento@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (61412, 'Barros da Cruz - EI', 'Campo Gomes, 638, Etelvina Carneiro, 75995-464 Novais do Oeste / RO', 'andre40@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (28713, 'Castro Ltda.', 'Recanto de Santos, Vila De Sá, 18350169 Pereira do Campo / RR', 'cferreira@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (52814, 'Santos', 'Ladeira de da Luz, 5, Céu Azul, 02666-423 da Luz do Campo / PE', 'gael-henriquesa@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (40315, 'Camargo', 'Núcleo de Vargas, 57, São Geraldo, 59704770 Rodrigues Verde / PR', 'marinacampos@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (68116, 'Novais e Filhos', 'Largo Correia, 3, Coração De Jesus, 46275477 Novaes / PI', 'elisamonteiro@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (17517, 'Garcia Caldeira e Filhos', 'Loteamento de Cavalcante, 40, Alta Tensão 2ª Seção, 30386-539 Lima de Santos / SE', 'maria-helenamendonca@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (39618, 'Siqueira', 'Chácara Moura, 15, Vitoria, 67176796 Farias / MG', 'dribeiro@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (68219, 'Fernandes', 'Residencial de Almeida, 6, Guaratã, 38535-450 Campos / MS', 'maria-laura44@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (65920, 'Mendonça', 'Condomínio Costela, 99, Piraja, 70989169 Pires da Prata / AM', 'aparecidacamila@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (30721, 'Abreu', 'Loteamento da Rocha, 36, São Gabriel, 22281-458 Pimenta do Norte / GO', 'novaisdavi-lucca@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (17322, 'Mendes da Rocha - ME', 'Setor de Leão, 40, Trevo, 71947-084 Peixoto da Prata / PB', 'erickviana@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (84123, 'Melo S/A', 'Quadra de Oliveira, 63, Corumbiara, 73649-593 da Rosa Alegre / SE', 'luiz-felipeviana@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (28724, 'Nunes', 'Aeroporto Benício Andrade, 94, Caetano Furquim, 05020-930 Rocha / RO', 'marquesian@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (28325, 'Araújo Ltda.', 'Vereda Heloísa Sampaio, 39, Funcionários, 55480-381 Mendes / TO', 'rhavi59@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (72326, 'Fonseca Melo S/A', 'Setor Cassiano, Custodinha, 58886-973 Melo de Nunes / RR', 'cecilianascimento@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (01327, 'Cavalcante', 'Colônia de Camargo, 6, Cidade Jardim, 13942-859 Alves / DF', 'das-nevesgabrielly@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (47128, 'Farias S/A', 'Trevo da Conceição, Casa Branca, 37976-674 Freitas da Serra / PI', 'manuelanogueira@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (79629, 'Pires', 'Avenida Luiza Aragão, 41, Vila Santa Rosa, 85174454 das Neves / DF', 'ayllacosta@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (53930, 'Moura Ltda.', 'Quadra de Gonçalves, 97, Maria Helena, 09129729 Vieira do Norte / AC', 'bmachado@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (36031, 'Machado Carvalho - EI', 'Avenida Maria Clara da Conceição, 98, São Cristóvão, 00989-311 Vasconcelos da Prata / RN', 'rafaelsiqueira@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (57632, 'Rodrigues', 'Vila Eloah Câmara, 13, Santa Margarida, 04186912 da Rocha / AM', 'emonteiro@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (01533, 'Martins', 'Aeroporto João Miguel da Mota, 89, Alto Das Antenas, 90773-573 Casa Grande de Goiás / PE', 'allana68@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (54234, 'Marques Fernandes Ltda.', 'Colônia de Ramos, 927, Marçola, 01646183 Lopes do Oeste / BA', 'dbarbosa@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (14335, 'Moura', 'Colônia de Pimenta, 5, Esplanada, 54712873 Rezende / SE', 'mgoncalves@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (52036, 'Sousa', 'Recanto de Rios, 26, Maria Helena, 66868-628 da Costa das Flores / RN', 'igomes@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (43637, 'Fonseca', 'Esplanada de Garcia, 284, Vila São Dimas, 54740718 Pimenta / PI', 'vitor-gabriel43@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (14038, 'Gonçalves - EI', 'Rua Nunes, 78, Conjunto Providencia, 53995748 Rodrigues de Siqueira / GO', 'cmacedo@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (12539, 'Nascimento - ME', 'Vereda Eduarda Melo, 45, São Lucas, 50870-519 Alves da Mata / PI', 'mpires@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (51640, 'Borges Ltda.', 'Esplanada Marques, 870, Satelite, 27355-788 Rezende / RN', 'ucosta@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (37041, 'Pires das Neves e Filhos', 'Alameda Albuquerque, 73, Canadá, 69175202 Silveira da Mata / DF', 'pborges@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (86342, 'Campos Ltda.', 'Rua Anthony Novaes, 48, João Pinheiro, 41070092 Marques / SE', 'ffreitas@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (79343, 'Barros', 'Morro de Brito, 18, Paulo Vi, 28226593 Mendonça / SE', 'lopesbella@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (35144, 'Sousa', 'Esplanada Nogueira, 84, Minas Brasil, 96349-628 Silva / AC', 'hcirino@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (60145, 'Dias', 'Via de Freitas, 982, Vila São Geraldo, 91701-137 Rodrigues do Campo / MA', 'casa-grandemaria-sophia@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (50946, 'Costela e Filhos', 'Aeroporto de Silva, 9, Lorena, 78679-076 Mendes da Mata / RS', 'rafael94@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (32847, 'Dias', 'Aeroporto Maria Sophia Ramos, 44, Cenaculo, 18138-227 Abreu de Dias / PI', 'julianalima@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (61448, 'Moreira Pinto Ltda.', 'Parque Alícia da Costa, 54, Ermelinda, 81591-762 Cunha / RJ', 'garciamariana@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (21049, 'da Costa S/A', 'Colônia Dante Martins, 18, Capitão Eduardo, 63606-493 Cavalcante / RS', 'arthur-miguelviana@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (54250, 'Souza - ME', 'Viaduto Anthony Garcia, Nova Pampulha, 25466114 Peixoto / CE', 'faragao@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (52951, 'Pires Andrade - ME', 'Residencial de Nascimento, 2, Jardim Dos Comerciarios, 52597-903 Barros / RJ', 'maria-juliaaraujo@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (59052, 'Ribeiro', 'Setor Dias, 32, Jardim Vitoria, 87272-904 Caldeira / MG', 'amandamarques@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (51953, 'Fonseca', 'Favela Kaique Cavalcante, 65, Vila Calafate, 03909891 Rios de Santos / RO', 'riosluiz-otavio@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (29354, 'Porto Freitas e Filhos', 'Campo Nogueira, 6, Conjunto Floramar, 45868-582 Vargas dos Dourados / PA', 'omontenegro@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (02855, 'Rodrigues', 'Passarela Ana Lívia Dias, 51, Vila Trinta E Um De Março, 49157662 Costa de Minas / AL', 'lnunes@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (46156, 'Pimenta Ltda.', 'Vereda Esther Souza, 301, Carmo, 31197-398 Garcia / RS', 'fonsecadaniel@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (41357, 'Monteiro - ME', 'Praia Fernando Novaes, Boa União 1ª Seção, 82250-711 Aragão / PA', 'eduardo00@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (72958, 'Santos', 'Rodovia Vieira, 83, Canaa, 00515924 Azevedo Paulista / SP', 'xrodrigues@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (38259, 'Barros Costa S.A.', 'Loteamento Câmara, 69, Virgínia, 96016654 Caldeira das Flores / TO', 'sabrinada-rosa@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (51460, 'Silveira', 'Vereda Benicio Pires, 39, Capitão Eduardo, 54708-194 Cunha do Sul / TO', 'diasarthur-miguel@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (90461, 'Jesus S/A', 'Rua de Nogueira, 55, Olhos D''água, 23612109 Costela do Campo / BA', 'henrycaldeira@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (79862, 'Albuquerque Castro Ltda.', 'Quadra de Macedo, 15, Ademar Maldonado, 82558-951 da Cruz de Goiás / RO', 'costelamariana@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (37663, 'Lima', 'Jardim Esther da Cruz, 96, Aparecida, 85815369 Siqueira / RO', 'isaac61@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (51864, 'Fogaça - EI', 'Via Vasconcelos, 85, João Alfredo, 50676-823 Andrade / CE', 'mendoncalivia@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (03965, 'da Rocha', 'Chácara Porto, Serra Verde, 05199416 Borges das Flores / RJ', 'gguerra@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (87666, 'da Mata', 'Morro Arthur Miguel Costa, 44, Ribeiro De Abreu, 37913-903 Costa / TO', 'emanuellydas-neves@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (50667, 'Rocha Ltda.', 'Chácara Garcia, 768, Lourdes, 45329-560 da Conceição Paulista / RS', 'ana-beatriz36@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (97668, 'Mendonça', 'Sítio Maria Alice Moura, 2, Vista Alegre, 94195384 Rodrigues / PR', 'silveiradavi-miguel@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (75469, 'Souza', 'Alameda Mendonça, 35, Vila Maloca, 77440664 Montenegro / MA', 'bento07@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (81970, 'Cardoso Ltda.', 'Ladeira Nascimento, 83, Vila Havaí, 62631035 Fernandes / RJ', 'laviniafreitas@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (13871, 'Pires Moreira S.A.', 'Chácara Andrade, 70, Carlos Prates, 43090-634 Almeida / ES', 'maria07@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (71272, 'Porto S/A', 'Aeroporto Maria Alice Brito, 47, Vila Das Oliveiras, 66152-944 Cavalcanti / MG', 'abreuluana@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (80673, 'Rios da Paz - EI', 'Jardim Davi Leão, São Gabriel, 58492-011 Vargas / PA', 'msilveira@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (49374, 'Macedo Montenegro e Filhos', 'Viela de Cavalcanti, 14, São Cristóvão, 49880-839 Peixoto da Serra / RS', 'hmacedo@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (52775, 'Freitas', 'Avenida da Cunha, 733, Santa Margarida, 11472-299 Cavalcante / PI', 'maysa44@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (65476, 'da Mota e Filhos', 'Chácara Fernandes, 70, Vila Sesc, 13509239 Moura / RR', 'dmoreira@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (70877, 'Ferreira', 'Campo Davi Lucca da Conceição, 6, Guarani, 63547801 Melo / AC', 'kgoncalves@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (82378, 'Lima e Filhos', 'Trecho de Vieira, 90, Vila Atila De Paiva, 31774-628 Moura / GO', 'tmendonca@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (07579, 'Cassiano', 'Núcleo Maria Julia Novaes, 17, Madri, 13256-574 Fogaça da Serra / PR', 'leaoheloisa@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (04380, 'Guerra', 'Setor da Rocha, Vale Do Jatoba, 84024982 Farias do Norte / SP', 'amendonca@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (89381, 'Aparecida', 'Vale José Miguel Brito, 46, Vila Satélite, 01448-524 da Rosa Verde / MT', 'josuecavalcante@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (48982, 'Ribeiro', 'Quadra Gomes, 222, Vila Madre Gertrudes 4ª Seção, 20661-188 Gonçalves Paulista / MG', 'benjamim62@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (52883, 'Oliveira S.A.', 'Campo Yasmin da Cruz, 49, Universo, 20515716 Viana do Amparo / MG', 'zmachado@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (25484, 'Vieira e Filhos', 'Largo Marcelo da Rosa, 4, Conjunto Serra Verde, 51481-300 Sá / TO', 'bianca14@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (74585, 'Pastor Fonseca - EI', 'Esplanada de Porto, Conjunto Jatoba, 17407557 Freitas da Praia / RN', 'andrademariah@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (41986, 'Ferreira Fonseca S.A.', 'Parque Léo Fogaça, 633, Santa Branca, 53186-301 da Conceição do Amparo / PB', 'santosgabrielly@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (15487, 'da Costa e Filhos', 'Feira Liam Moura, 86, Paraíso, 60164-139 Silveira de Cirino / ES', 'oliver73@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (60588, 'Alves', 'Condomínio Amanda Almeida, 13, São Sebastião, 72777694 Martins / DF', 'liam98@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (30789, 'Silveira', 'Estrada de Abreu, 6, Liberdade, 18121065 Silveira / AL', 'valentinaabreu@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (73590, 'das Neves', 'Morro de Moura, 84, Vila Boa Vista, 32332027 Camargo / MG', 'fogacaenzo@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (80391, 'Martins', 'Fazenda Dias, 62, São Paulo, 09646-027 Câmara / PA', 'da-luzaurora@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (47392, 'Montenegro Machado - EI', 'Ladeira de Dias, 407, Tres Marias, 05002-328 Dias / SE', 'qaparecida@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (27893, 'Novaes da Cruz - EI', 'Rodovia Laís Oliveira, 61, Vila Jardim São José, 87772320 Siqueira Paulista / PA', 'ana-liz27@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (43894, 'Viana da Cunha S/A', 'Quadra Teixeira, 23, Jardim Atlântico, 17977750 Melo / MS', 'upastor@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (29395, 'Leão - EI', 'Passarela Yago Porto, 3, Santana Do Cafezal, 75259-999 Aragão de Fernandes / AL', 'allana29@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (72696, 'Rios Cavalcanti - EI', 'Setor Gomes, 43, Pedreira Padro Lopes, 67342-063 Cavalcanti / PR', 'csouza@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (04997, 'Montenegro - EI', 'Lagoa de Sampaio, 90, Conjunto Providencia, 41531-820 Barbosa da Serra / RJ', 'saragao@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (07898, 'Casa Grande Macedo Ltda.', 'Fazenda Gustavo Barros, 149, Zilah Sposito, 77402767 Melo / TO', 'dlima@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (69199, 'Rios Camargo - EI', 'Favela de Farias, 4, Santa Monica, 79153198 Ribeiro das Flores / RJ', 'rda-paz@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (350100, 'Rocha', 'Núcleo Calebe Câmara, 42, Universo, 58154356 Pastor / PA', 'siqueiragabrielly@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (930101, 'Siqueira', 'Ladeira de Castro, 15, Paraíso, 00365273 Cassiano da Mata / PR', 'ssa@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (047102, 'Sales S/A', 'Área Maitê Teixeira, 35, Pompéia, 77615-783 Mendonça / PE', 'ppinto@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (103103, 'da Cunha', 'Colônia Benjamim Machado, 68, Madre Gertrudes, 30566-648 Vieira da Mata / MG', 'siqueiraana-laura@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (382104, 'Martins Ltda.', 'Estrada de Marques, 8, Conjunto Minas Caixa, 75198-948 Carvalho de Brito / MT', 'jose-pedro84@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (084105, 'Martins Rocha e Filhos', 'Lago Levi Lopes, 76, Conjunto Serra Verde, 45900-852 Abreu dos Dourados / PE', 'oliveiratheodoro@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (190106, 'Jesus', 'Lago Martins, 44, Taquaril, 56841-046 Rezende / BA', 'da-mataayla@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (684107, 'da Conceição - EI', 'Praia Breno Sales, 53, Horto Florestal, 99501064 Lima / DF', 'maria-flor33@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (586108, 'Nascimento Duarte - EI', 'Via Fernandes, 46, Jardim Atlântico, 05709-669 Guerra / SP', 'igorcardoso@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (394109, 'Dias Ltda.', 'Pátio Jesus, 97, Vila Formosa, 16859118 Sampaio da Mata / PR', 'rsousa@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (803110, 'Carvalho', 'Estrada de Cirino, Santa Branca, 87784-977 Albuquerque / GO', 'alexandreaparecida@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (657111, 'Nunes', 'Área Nunes, Conjunto Floramar, 08575-684 Azevedo / TO', 'davi-lucas66@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (138112, 'Ribeiro', 'Colônia de Sousa, 71, Leonina, 18358826 Ribeiro Alegre / AL', 'maria-cecilia09@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (018113, 'Pimenta S.A.', 'Área Ana Liz Guerra, 835, Alto Vera Cruz, 66016928 Sousa de Gonçalves / CE', 'kbarbosa@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (243114, 'Araújo Marques Ltda.', 'Morro de Silva, 96, Grotinha, 80751-059 Câmara / MS', 'rebecabarros@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (986115, 'Pires e Filhos', 'Lago da Rocha, 98, Pirineus, 33594674 Barbosa / DF', 'maria-ceciliamontenegro@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (346116, 'Teixeira - EI', 'Distrito Benjamin Fonseca, 57, Jardim Leblon, 64160-295 da Cruz Paulista / MA', 'matheus05@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (062117, 'Monteiro - EI', 'Avenida Caldeira, 96, São Damião, 88717-084 Castro / PI', 'almeidakevin@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (427118, 'Leão', 'Área de Porto, 12, Bonsucesso, 80562-453 Gonçalves de da Rosa / TO', 'ana-sophia06@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (461119, 'da Cruz - EI', 'Estação de Montenegro, 8, Vila Piratininga, 54018927 Abreu / BA', 'alexiaborges@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (479120, 'Vasconcelos', 'Lagoa Yasmin Araújo, 84, Tirol, 76858-118 Souza / MA', 'almeidajose-pedro@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (931121, 'Oliveira', 'Lago Lopes, 19, Vila Madre Gertrudes 3ª Seção, 22264034 Lopes / SP', 'da-rochanoah@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (967122, 'Leão Lima S.A.', 'Rua de Souza, Lorena, 75022741 Costa do Sul / PB', 'vianagael-henrique@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (673123, 'Ramos da Paz - EI', 'Viaduto Renan Silva, 60, Vila Da Ária, 98389-669 Moreira / PE', 'silveiraotto@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (160124, 'Vargas', 'Ladeira de Casa Grande, 72, Madre Gertrudes, 51703301 Novais / PR', 'alopes@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (082125, 'da Luz', 'Conjunto de Silva, 67, Vila São Geraldo, 25135-672 Pacheco / RN', 'dcavalcante@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (598126, 'Duarte', 'Rodovia Costela, 34, Silveira, 47709818 Marques Alegre / AC', 'joao-felipe73@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (581127, 'Leão Sales - EI', 'Morro Nascimento, Aparecida, 62767532 Ramos de Viana / DF', 'ksilva@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (629128, 'Rocha e Filhos', 'Jardim de Sampaio, 92, João Alfredo, 45020-662 Lima / TO', 'jadecavalcanti@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (391129, 'Jesus', 'Fazenda Yago Cirino, 96, Coqueiros, 53734421 da Paz do Norte / PB', 'luizanogueira@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (326130, 'Gomes', 'Travessa Machado, 71, Vila Santa Rosa, 57668-455 da Rosa da Mata / TO', 'luiz-otaviobrito@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (364131, 'Martins', 'Morro Siqueira, 2, Vila Da Paz, 57080788 Costa / AM', 'oliveiraluiz-otavio@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (937132, 'Abreu e Filhos', 'Avenida Valentim da Rosa, 602, Bernadete, 56408858 Cirino de Goiás / PI', 'rezendemaysa@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (508133, 'Novais Marques S.A.', 'Praia Mendes, Satelite, 84795843 Oliveira das Flores / RJ', 'henry-gabriel73@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (695134, 'da Mota S/A', 'Colônia João Felipe Montenegro, Bacurau, 13511272 da Costa / AC', 'lucassa@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (754135, 'Montenegro', 'Estação Júlia Sales, São Pedro, 23865-650 Pereira do Galho / PI', 'da-rochamaria-cecilia@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (634136, 'Silva - EI', 'Favela de Leão, 30, Ermelinda, 66016-284 Cassiano de Goiás / PA', 'das-neveselisa@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (067137, 'Brito Porto - EI', 'Fazenda de Moraes, 38, Cidade Jardim, 07744084 Porto do Oeste / PE', 'costelasophie@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (914138, 'Rezende Rodrigues - EI', 'Estrada Sales, 88, Vila Antena Montanhês, 93785875 da Rocha da Mata / RO', 'snovaes@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (283139, 'da Cruz Cardoso Ltda.', 'Pátio de Pimenta, 91, Conjunto Califórnia I, 05723349 Pires / MG', 'fmacedo@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (534140, 'Nascimento', 'Conjunto Guerra, 5, São Tomaz, 22649462 Viana / MT', 'usa@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (209141, 'Monteiro', 'Aeroporto Vasconcelos, 11, Conjunto Jardim Filadélfia, 02235973 Gomes das Pedras / PA', 'marianemoraes@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (246142, 'Santos', 'Núcleo Teixeira, 576, Dom Cabral, 34982316 Sousa / PI', 'jmachado@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (120143, 'Cardoso', 'Jardim Caio Silveira, 31, Nova Gameleira, 38728-793 Dias / SC', 'raelmelo@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (581144, 'Pires', 'Vale Cavalcante, 7, São José, 29014-579 Rodrigues / PB', 'maria-florcarvalho@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (072145, 'Farias - ME', 'Vereda de da Cunha, 742, Padre Eustáquio, 57398-658 Fogaça / TO', 'vasconcelosvitoria@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (937146, 'da Luz - EI', 'Jardim da Mata, Vila Ecológica, 73864045 Cunha do Amparo / MG', 'laura92@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (065147, 'Moura', 'Estação Eduarda Campos, 53, Barroca, 98816023 Fogaça / MS', 'mateusgarcia@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (718148, 'da Mota - EI', 'Setor Cassiano, 836, Jatobá, 10027328 Araújo do Galho / AL', 'marcela81@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (891149, 'Ribeiro', 'Vereda Heloísa Pereira, 95, Ápia, 96826526 Montenegro / SC', 'abreualexandre@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (120150, 'Cavalcanti', 'Rodovia Ian Vargas, 40, Vila Cemig, 66542-424 Silveira do Amparo / DF', 'maria-vitoriavargas@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (608151, 'Mendonça', 'Avenida Gonçalves, 300, Camponesa 2ª Seção, 71305-998 Correia da Prata / SC', 'rodrigo17@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (735152, 'Caldeira Vargas e Filhos', 'Favela Vitória Garcia, 273, Nossa Senhora De Fátima, 38406143 Rocha das Pedras / SP', 'vargasnoah@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (680153, 'da Rosa', 'Sítio da Mota, 97, Alto Barroca, 96955-589 Cirino de Moura / PE', 'pribeiro@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (391154, 'Alves S/A', 'Passarela João Guilherme Guerra, 5, Novo Aarão Reis, 01835-337 Pimenta de Goiás / PI', 'ncavalcanti@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (926155, 'Pires', 'Vila Rios, 65, Vila Engenho Nogueira, 30983687 Abreu Grande / SE', 'caldeirahelena@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (187156, 'Nascimento Cirino - EI', 'Avenida Cecilia Viana, 24, Beira Linha, 68504880 Rocha / SE', 'paulo33@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (497157, 'da Luz Porto - EI', 'Alameda de Aparecida, 19, Santa Isabel, 62398-912 Silveira / RO', 'caldeiralais@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (265158, 'Rodrigues Machado S.A.', 'Esplanada de das Neves, 838, Jardim São José, 58630-354 Jesus de Ramos / PE', 'leticiaaraujo@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (806159, 'Dias - EI', 'Residencial Bella Cardoso, 57, Solar Do Barreiro, 01742455 Mendes / RJ', 'mateus92@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (287160, 'Oliveira', 'Núcleo Lopes, Serra Do Curral, 36715-826 Machado do Norte / BA', 'abreualicia@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (195161, 'Cirino Guerra e Filhos', 'Travessa de Duarte, 18, Apolonia, 91563-193 Nunes de Dias / MT', 'eda-cunha@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (918162, 'Macedo', 'Vale de Garcia, 1, Penha, 73568-375 Viana / BA', 'heitor30@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (347163, 'Castro e Filhos', 'Vereda Marcelo Vieira, 50, Jatobá, 71858500 da Conceição / AP', 'rhavida-paz@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (693164, 'Silva', 'Morro de Araújo, Nova Suíça, 30329402 Freitas Grande / SC', 'dvargas@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (397165, 'Leão', 'Rua de Ferreira, 82, Vila União, 95668165 Casa Grande / PR', 'brendacasa-grande@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (835166, 'Vieira', 'Lagoa Lima, 4, Vila São Francisco, 98361-985 Alves / RS', 'wandrade@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (217167, 'da Paz', 'Favela Costa, Cenaculo, 11367-807 Fernandes / PA', 'nataliaviana@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (167168, 'Andrade Siqueira e Filhos', 'Lagoa Novaes, 15, Vila Da Ária, 48798852 Barros da Mata / MG', 'mcardoso@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (294169, 'Santos Farias e Filhos', 'Travessa de Sousa, 1, Manacas, 02905293 Barbosa / RN', 'caioteixeira@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (928170, 'Viana e Filhos', 'Avenida de da Mota, 29, Vila Santa Rosa, 18497622 Garcia / SP', 'leo40@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (352171, 'Jesus S/A', 'Via Albuquerque, 66, Pedreira Padro Lopes, 13600237 Aragão / SE', 'helenanunes@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (189172, 'Fernandes S.A.', 'Favela Evelyn Cavalcante, 9, Calafate, 84709-577 Mendes da Prata / RO', 'gomesotavio@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (847173, 'Pastor Rodrigues Ltda.', 'Fazenda Dias, 605, Frei Leopoldo, 80680246 da Mata do Norte / RJ', 'nascimentojoao-pedro@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (594174, 'Jesus da Rocha - ME', 'Viela Lopes, 438, Casa Branca, 94097-573 Porto / PR', 'nunesjose-miguel@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (681175, 'Oliveira S.A.', 'Trecho Julia Guerra, 3, Boa União 1ª Seção, 83488625 da Luz / BA', 'hlima@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (438176, 'Andrade', 'Recanto Ayla Ramos, 39, Penha, 55172783 Campos / PR', 'luisa34@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (763177, 'Sampaio', 'Vereda Rafael Machado, 86, Embaúbas, 45834-555 da Cunha de Caldeira / TO', 'fogacalais@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (426178, 'Fernandes Macedo S/A', 'Parque Moura, 47, Novo Tupi, 03095-099 Araújo Alegre / RO', 'maria-sophiasousa@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (165179, 'Rodrigues Guerra e Filhos', 'Conjunto Barros, 97, Saudade, 73715-154 Pacheco do Campo / GO', 'eloa47@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (630180, 'Borges e Filhos', 'Rua Theo Farias, Santa Rita De Cássia, 63252-748 Montenegro / AL', 'kcaldeira@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (109181, 'Ribeiro', 'Vale Henry Freitas, 19, Vila Nova Dos Milionarios, 31334028 Aragão do Oeste / MA', 'mendesmaya@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (148182, 'Lima', 'Vale Cecília Teixeira, 52, Xodo-Marize, 10457-622 Silva de Moura / RJ', 'castroana-sophia@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (615183, 'Pinto Sá S/A', 'Praça Mendonça, 53, Tirol, 24240-834 da Paz de Monteiro / CE', 'isis62@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (017184, 'Rodrigues Albuquerque - ME', 'Recanto Costela, 15, Vila Havaí, 87992871 Lopes dos Dourados / PI', 'qcamara@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (637185, 'Nunes - EI', 'Ladeira Dias, Vila São Rafael, 92909208 Dias de Monteiro / MA', 'allana25@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (817186, 'Mendonça', 'Distrito Theodoro Cassiano, 261, Urca, 76537750 Fernandes de Dias / SP', 'vfarias@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (394187, 'Vieira Cavalcanti - EI', 'Quadra Rios, 88, Eymard, 30608362 Cavalcanti / PB', 'joao-miguel91@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (897188, 'Azevedo', 'Travessa Moreira, Capitão Eduardo, 58965351 Campos de Machado / RS', 'ramosmaria-fernanda@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (029189, 'Sá Fonseca e Filhos', 'Praia de Moura, Vila Minaslandia, 66840907 Abreu de Albuquerque / ES', 'nunesemanuelly@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (136190, 'Campos', 'Morro de Nascimento, 70, Vila Nova Cachoeirinha 2ª Seção, 35763-397 Lima / CE', 'araujorebeca@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (768191, 'Nunes Nascimento e Filhos', 'Passarela de Pastor, 28, Cônego Pinheiro 1ª Seção, 97376588 Jesus do Oeste / PI', 'martinsmaria-isis@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (071192, 'da Conceição Ltda.', 'Conjunto de Borges, 246, Santa Terezinha, 52362683 Gonçalves / CE', 'cirinobreno@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (918193, 'Souza Monteiro S/A', 'Jardim Albuquerque, Pompéia, 31542236 Sousa / RJ', 'matteomendes@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (206194, 'Novaes Silva e Filhos', 'Vereda Ribeiro, 1, Vila Copacabana, 02979583 Novaes / RR', 'bda-luz@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (608195, 'da Rocha Barbosa - EI', 'Campo de Almeida, 41, Vila Jardim São José, 66640-864 da Paz Verde / MG', 'cavalcantimaysa@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (287196, 'Cavalcante', 'Praça Sampaio, 174, Vitoria Da Conquista, 09769-916 Vasconcelos / MG', 'anthony-gabrielcamara@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (042197, 'Cunha e Filhos', 'Parque de Cunha, 52, Vista Do Sol, 73853909 Vargas do Campo / SP', 'pedro-miguel91@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (139198, 'Machado', 'Trecho de Castro, 9, São Bernardo, 17540-945 da Cunha Verde / TO', 'maria-laura72@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (940199, 'Viana', 'Pátio Eloah Câmara, São Benedito, 19901-242 Monteiro / TO', 'ana-carolinaalves@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (127200, 'Cassiano Correia S/A', 'Vila Martins, 615, Leonina, 36795071 Alves de Minas / MS', 'melissa66@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (804201, 'da Costa e Filhos', 'Colônia Correia, 329, Juliana, 30206629 Moura de Campos / AM', 'iancavalcanti@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (753202, 'Sá Rocha S/A', 'Campo Aurora Teixeira, 395, Vila Cemig, 02615-331 Pereira / RJ', 'barbarapimenta@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (768203, 'da Rosa e Filhos', 'Conjunto Costa, São Bento, 05046-357 Oliveira / MT', 'mmendonca@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (309204, 'Moraes', 'Fazenda Duarte, Vila Aeroporto, 85833-110 Teixeira / MA', 'casa-grandediogo@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (819205, 'Moura e Filhos', 'Loteamento Eduarda da Conceição, 12, Cabana Do Pai Tomás, 49612779 Aparecida do Oeste / DF', 'aliciapacheco@example.org', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (051206, 'Jesus Jesus S.A.', 'Via Jesus, 960, Santa Sofia, 84450-409 Sá do Amparo / SC', 'olivia05@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (512207, 'Viana Rezende S.A.', 'Fazenda de Oliveira, 82, São Jorge 2ª Seção, 42307-670 Duarte do Campo / AL', 'casa-grandecamila@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (693208, 'Viana', 'Recanto Benjamin Moreira, 1, Europa, 46478939 Gomes de Goiás / RR', 'bcaldeira@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (238209, 'da Mota', 'Fazenda Thiago Aragão, 7, Vila Nova Gameleira 3ª Seção, 46058-798 Correia / SE', 'melissavieira@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (650210, 'Lima', 'Largo Souza, 919, Vila Copasa, 24299366 Santos / SC', 'novaesarthur@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (647211, 'Duarte', 'Ladeira Valentina Ferreira, 24, Candelaria, 40995-049 Cardoso do Sul / DF', 'bernardo99@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (702212, 'Araújo Siqueira - EI', 'Colônia Pereira, 3, João Pinheiro, 18574-101 Rocha do Sul / PI', 'caio00@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (873213, 'Ribeiro', 'Viaduto da Cruz, 5, Fernão Dias, 47522376 Nogueira / RJ', 'rafaelmoura@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (654214, 'Borges Duarte e Filhos', 'Rua de Teixeira, 76, Jardim Vitoria, 48540-875 Abreu / TO', 'palbuquerque@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (308215, 'Sá - EI', 'Praça de da Rocha, 161, Alto Caiçaras, 25190780 Andrade / SC', 'pedroguerra@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (127216, 'Pires da Luz - ME', 'Vila Juliana Barros, 920, União, 04237-392 Novais das Pedras / PI', 'azevedopedro@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (591217, 'Nunes - EI', 'Lagoa de Brito, Itaipu, 16674-282 Machado / RS', 'jrocha@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (406218, 'Sousa', 'Estrada Gabrielly Lopes, 6, Novo Glória, 03578483 Araújo / SE', 'oda-paz@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (876219, 'Pastor e Filhos', 'Colônia de Dias, Vila Cloris, 61771665 Araújo / CE', 'garciavicente@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (621220, 'Vieira Almeida S.A.', 'Sítio de Garcia, 72, Castanheira, 65874-543 Câmara de da Cruz / PR', 'ryan47@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (685221, 'Sales Cassiano - ME', 'Condomínio Nascimento, Unidas, 60325668 Campos de Minas / ES', 'alice10@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (026222, 'Ribeiro e Filhos', 'Via de Santos, 256, Goiania, 67194-941 Caldeira / MT', 'nascimentonatalia@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (642223, 'Pastor Ltda.', 'Residencial Mendonça, Castelo, 63332-112 Rios do Campo / ES', 'bfonseca@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (510224, 'Câmara', 'Fazenda de Aragão, 16, Lorena, 62256-153 Barros / RJ', 'boliveira@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (673225, 'Nascimento Abreu S.A.', 'Quadra de Moreira, 12, Primeiro De Maio, 06508-548 Rios da Praia / RS', 'fariasyan@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (698226, 'Macedo - ME', 'Avenida Luiza Pimenta, 78, Maria Tereza, 14925077 Camargo do Galho / RJ', 'larissa73@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (728227, 'Montenegro Rocha e Filhos', 'Residencial Silveira, 51, Bairro Das Indústrias Ii, 19187362 Almeida de Goiás / AM', 'uandrade@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (590228, 'Novais S.A.', 'Alameda Rocha, Varzea Da Palma, 97634-831 Abreu Alegre / RO', 'bianca89@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (051229, 'Peixoto Cunha - EI', 'Distrito da Rosa, 44, Venda Nova, 06734879 Moreira de Goiás / PA', 'yuricaldeira@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (751230, 'Santos', 'Esplanada Thomas Moura, 47, Independência, 31998477 da Rocha Alegre / CE', 'silvavalentina@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (573231, 'Andrade - EI', 'Favela de das Neves, 123, Dona Clara, 99699887 Costela de Lopes / DF', 'kaiqueborges@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (678232, 'Vasconcelos', 'Residencial Cunha, 68, Apolonia, 57069-623 Peixoto / MA', 'barbosaana-cecilia@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (605233, 'Albuquerque S/A', 'Largo Alves, 53, Nova Esperança, 80053232 Moreira / MG', 'adias@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (481234, 'Nogueira', 'Residencial Ribeiro, 29, Jaraguá, 90835-348 Guerra / MT', 'liamda-paz@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (386235, 'Aparecida', 'Núcleo Dias, 65, Vila Ecológica, 84557-196 Peixoto dos Dourados / PR', 'anna-lizviana@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (346236, 'Garcia', 'Via de Fonseca, 98, Tiradentes, 27587-467 Moraes das Pedras / TO', 'pastorlara@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (963237, 'Andrade - ME', 'Trecho Gustavo Pastor, Zilah Sposito, 54333-122 da Paz do Oeste / MA', 'costasamuel@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (862238, 'Souza', 'Passarela de Cavalcante, 8, Vila Madre Gertrudes 3ª Seção, 46557-271 Novais / ES', 'maria-isissantos@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (924239, 'Marques Casa Grande e Filhos', 'Estação Enrico Cunha, Vila Fumec, 81891439 da Rosa Alegre / RN', 'wcamargo@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (635240, 'Nunes', 'Colônia Pastor, 3, Nova Suíça, 97969-772 Novaes / TO', 'aurora04@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (594241, 'da Luz', 'Estação de Gomes, 57, Dom Joaquim, 67170-233 Porto de das Neves / MG', 'ida-luz@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (327242, 'Costela Ltda.', 'Sítio de Nogueira, 52, Vila Antena, 27963-467 Fonseca / MG', 'leandroda-cruz@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (684243, 'Costela', 'Via de Marques, 94, Mangueiras, 59740-478 Cavalcanti / GO', 'eduarda89@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (502244, 'Leão', 'Morro Moreira, 43, Carmo, 85823034 Barros / RN', 'da-costaapollo@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (962245, 'Lima', 'Alameda Sara Garcia, 77, Vila São Gabriel Jacui, 98445-410 Cardoso Alegre / DF', 'cecilia54@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (425246, 'das Neves', 'Via Casa Grande, 296, Centro, 87020534 Rios / DF', 'natalianunes@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (815247, 'Santos Ltda.', 'Jardim Melo, 42, Esperança, 21115-363 Mendonça / RN', 'otaviopeixoto@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (084248, 'Macedo', 'Área Nunes, 45, Vila São Dimas, 91788292 Cavalcante das Pedras / PI', 'freitasheitor@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (874249, 'Pereira', 'Quadra Caldeira, 14, Maria Goretti, 15934-320 da Paz / SP', 'dpires@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (926250, 'da Paz S/A', 'Viela de Camargo, 5, Caetano Furquim, 79981155 Nascimento Grande / DF', 'britocamila@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (629251, 'Moraes S/A', 'Trevo Dante Nunes, 15, Conjunto Novo Dom Bosco, 09943-792 Aparecida da Serra / AC', 'fernandaramos@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (251252, 'Vargas', 'Praia Luísa Abreu, 90, Calafate, 20721-115 Sales / MG', 'gabriel83@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (409253, 'da Mota - ME', 'Colônia Sá, 89, Minas Brasil, 13870147 da Cunha Grande / SP', 'maria90@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (647254, 'Campos Melo - EI', 'Esplanada Marcos Vinicius Dias, 566, Dom Cabral, 10899-986 Guerra de da Luz / RN', 'cirinoraul@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (897255, 'Barros', 'Residencial Isadora Aparecida, 59, Vila Nova Gameleira 3ª Seção, 25047-800 Moura do Norte / MA', 'agoncalves@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (350256, 'Rocha - ME', 'Viela Emanuelly Santos, Ápia, 65279-437 Aparecida do Amparo / TO', 'cassianorafaela@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (546257, 'Jesus Camargo e Filhos', 'Feira de Farias, 10, Alto Caiçaras, 44306-185 Novaes / PE', 'tvieira@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (627258, 'Martins Macedo - EI', 'Área da Cunha, 79, Vila Do Pombal, 65862569 Fernandes da Mata / RO', 'machadopedro-miguel@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (962259, 'Mendonça', 'Morro Alana Rodrigues, 5, Alto Barroca, 75383189 Gomes / AP', 'melohenrique@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (516260, 'das Neves S/A', 'Fazenda de da Rosa, 970, Santo Antônio, 00876-886 Brito / AP', 'maria-fernandamoreira@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (821261, 'Lima', 'Feira Sophie Siqueira, 48, Califórnia, 94567-946 Cassiano / RJ', 'meloravi-lucca@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (952262, 'Azevedo Martins - ME', 'Chácara de Rezende, Liberdade, 64397005 Brito / AP', 'ana-julia78@example.com', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (267263, 'Macedo da Paz - ME', 'Feira de Cavalcante, São Benedito, 69002-477 Sousa do Campo / CE', 'dmonteiro@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (632264, 'Peixoto Fogaça Ltda.', 'Trevo Silveira, 30, Jardim Dos Comerciarios, 07751-779 Cunha da Prata / RJ', 'julia56@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (715265, 'da Costa', 'Praia Araújo, 98, Vila Calafate, 03111518 Souza das Flores / RR', 'lais79@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (410266, 'Moura', 'Loteamento de Rezende, 99, Vila Madre Gertrudes 3ª Seção, 58531-732 Barros de Garcia / MG', 'portogael-henrique@example.org', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (369267, 'Nascimento', 'Via Calebe Costela, 19, Flavio Marques Lisboa, 97251733 Gonçalves de Silva / AP', 'brayansampaio@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (412268, 'Vargas Teixeira - EI', 'Via de Pereira, 96, Vila Ouro Minas, 72061416 Lopes / PE', 'raulda-mota@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (417269, 'Sá', 'Sítio Machado, 63, João Paulo Ii, 38878592 Nunes / DF', 'mfogaca@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (894270, 'Ramos e Filhos', 'Jardim Cassiano, 36, Vila Betânia, 51807-762 Ramos Alegre / PB', 'qteixeira@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (263271, 'Machado', 'Largo Machado, 352, Conjunto Providencia, 01459-036 Mendes / DF', 'murilosampaio@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (610272, 'da Rosa', 'Viela Moraes, 726, Vila São João Batista, 48651-818 Peixoto dos Dourados / AC', 'karagao@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (137273, 'Albuquerque', 'Lago Fogaça, 53, Santo André, 66920-493 Marques / PI', 'ana-luizada-conceicao@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (103274, 'Duarte da Mota e Filhos', 'Trecho Vinícius Casa Grande, Nossa Senhora Do Rosário, 62203053 Siqueira de Cassiano / RJ', 'olivermoreira@example.com', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (954275, 'da Rosa Ramos Ltda.', 'Residencial de da Cruz, 30, São Jorge 3ª Seção, 09929-468 Martins / RJ', 'thomascamara@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (890276, 'Camargo S.A.', 'Setor Cirino, 63, Carlos Prates, 46239-862 Dias de da Rosa / RN', 'ana-claramoreira@example.com', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (472277, 'Barbosa - ME', 'Via Souza, 77, Vila Nova Dos Milionarios, 85344-200 Alves Verde / PI', 'rmontenegro@example.net', 5);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (457278, 'Cirino - ME', 'Recanto Larissa Moreira, 5, Santa Cruz, 08099201 Monteiro / PI', 'mnovais@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (739279, 'Camargo Fernandes S/A', 'Avenida Gabriel Pereira, 692, Jardim Atlântico, 90154666 da Mata de Garcia / MS', 'ubarros@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (601280, 'Macedo Teixeira S/A', 'Viaduto Lima, 92, Barão Homem De Melo 3ª Seção, 85001-205 Rocha Alegre / PB', 'milenamarques@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (095281, 'Mendonça Dias Ltda.', 'Campo de Marques, 89, Caiçara - Adelaide, 91754-765 Casa Grande do Sul / SP', 'maria-luisafreitas@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (346282, 'Costa', 'Avenida Oliver Fogaça, 118, Vila Novo São Lucas, 92932-194 Moraes da Mata / SP', 'evelynvieira@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (219283, 'Sousa - ME', 'Trecho de Nunes, Delta, 25563126 Sá / PR', 'miguelcampos@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (749284, 'Lima', 'Trecho de Almeida, 7, Dom Bosco, 60748-231 Vieira / ES', 'antoniofernandes@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (214285, 'da Cunha - ME', 'Trevo Camargo, 13, Betânia, 68088144 Leão Paulista / DF', 'gabrielly00@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (957286, 'Peixoto', 'Feira Kamilly Barros, Cabana Do Pai Tomás, 77370729 da Cunha / RO', 'andradegabriela@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (518287, 'Marques', 'Fazenda Vieira, 18, Santa Lúcia, 33369-603 Câmara Paulista / AC', 'psales@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (684288, 'Vieira', 'Morro de Melo, 56, São Luiz, 47564018 Camargo / RR', 'sousaluisa@example.com', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (645289, 'Sales S.A.', 'Estrada Sá, Nova Cintra, 50087905 da Cunha / PI', 'sarah12@example.org', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (328290, 'Dias', 'Loteamento Borges, 3, Vila Jardim Montanhes, 03175788 Jesus dos Dourados / MT', 'aparecidaravy@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (248291, 'Monteiro S/A', 'Praia Gabrielly Araújo, 18, Vila Paraíso, 66553658 Moraes do Norte / RN', 'gnogueira@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (801292, 'Correia - EI', 'Chácara Benício Carvalho, 91, São Jorge 3ª Seção, 95180-393 Pereira do Campo / SE', 'brunomartins@example.com', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (540293, 'Teixeira', 'Esplanada Aragão, 1, Vila Jardim Alvorada, 94717752 Rezende do Sul / AM', 'gustavo-henriquesilva@example.net', 1);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (371294, 'Mendonça - EI', 'Vereda Ravi da Mota, 5, Cônego Pinheiro 2ª Seção, 48854960 da Cruz das Flores / RR', 'mpinto@example.net', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (208295, 'Caldeira Cavalcante - ME', 'Área de Guerra, Salgado Filho, 77874-401 Alves Paulista / MT', 'sousaaylla@example.net', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (108296, 'Barbosa - ME', 'Sítio Pietro Cirino, 788, Betânia, 06913-631 Câmara / SP', 'jadeferreira@example.org', 3);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (236297, 'Rocha - EI', 'Vila Teixeira, Santa Tereza, 67362-663 Albuquerque de Goiás / SC', 'drios@example.net', 2);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (617298, 'Brito Fonseca e Filhos', 'Sítio Vinícius da Luz, Conjunto Paulo Vi, 88750-777 da Mata Verde / MA', 'hgoncalves@example.org', 4);
INSERT INTO IMOBILIARIA (cnpj, nome, ende, email, aval) VALUES (259299, 'Barbosa e Filhos', 'Núcleo Novaes, 494, Europa, 22902092 Monteiro / RR', 'bento71@example.com', 4);
